# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

dpGLM_mcmc <- function(y, X, weights, K, fix, family, mcmc, epsilon, leapFrog, n_display, hmc_iter) {
    .Call('_hdpGLM_dpGLM_mcmc', PACKAGE = 'hdpGLM', y, X, weights, K, fix, family, mcmc, epsilon, leapFrog, n_display, hmc_iter)
}

